# Generated by Django 5.0.6 on 2024-06-30 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_IP', models.GenericIPAddressField(blank=True, null=True)),
                ('action_datetime', models.DateTimeField(auto_now=True)),
                ('changed_object', models.CharField(max_length=40)),
                ('event_category', models.CharField(max_length=40)),
                ('user_agent_info', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action', models.CharField(max_length=40)),
                ('change_summary', models.CharField(max_length=199)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
